name = "Whirl"
uuid = "deeadbaa-8870-422d-a790-697f4d0ce6cf"
authors = ["Lars Frogner <lars_frogner@hotmail.com>"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
